name: ML Project CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup  # Run only after the setup job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests with pytest
      run: pytest tests/

  train-model:
    name: Train Model
    runs-on: ubuntu-latest
    needs: test  # Run only after tests pass

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train the model
      run: python src/train.py
